<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bxamzox' shared service.

return $this->privates['.service_locator.bxamzox'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\Api\\AuthorController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\AuthorController::delete' => ['privates', '.service_locator.XxBBP_c', 'get_ServiceLocator_XxBBPCService.php', true],
    'App\\Controller\\AuthorController::single' => ['privates', '.service_locator.XxBBP_c', 'get_ServiceLocator_XxBBPCService.php', true],
    'App\\Controller\\AuthorController::update' => ['privates', '.service_locator.XxBBP_c', 'get_ServiceLocator_XxBBPCService.php', true],
    'App\\Controller\\BookController::delete' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController::single' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController::update' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\Api\\AuthorController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\AuthorController:delete' => ['privates', '.service_locator.XxBBP_c', 'get_ServiceLocator_XxBBPCService.php', true],
    'App\\Controller\\AuthorController:single' => ['privates', '.service_locator.XxBBP_c', 'get_ServiceLocator_XxBBPCService.php', true],
    'App\\Controller\\AuthorController:update' => ['privates', '.service_locator.XxBBP_c', 'get_ServiceLocator_XxBBPCService.php', true],
    'App\\Controller\\BookController:delete' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController:single' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
    'App\\Controller\\BookController:update' => ['privates', '.service_locator.PbXwDqA', 'get_ServiceLocator_PbXwDqAService.php', true],
], [
    'App\\Controller\\Api\\AuthorController::setViewHandler' => '?',
    'App\\Controller\\AuthorController::delete' => '?',
    'App\\Controller\\AuthorController::single' => '?',
    'App\\Controller\\AuthorController::update' => '?',
    'App\\Controller\\BookController::delete' => '?',
    'App\\Controller\\BookController::single' => '?',
    'App\\Controller\\BookController::update' => '?',
    'App\\Controller\\Api\\AuthorController:setViewHandler' => '?',
    'App\\Controller\\AuthorController:delete' => '?',
    'App\\Controller\\AuthorController:single' => '?',
    'App\\Controller\\AuthorController:update' => '?',
    'App\\Controller\\BookController:delete' => '?',
    'App\\Controller\\BookController:single' => '?',
    'App\\Controller\\BookController:update' => '?',
]);
