<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\AdminBundle\Command\ListAdminCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Command/ListAdminCommand.php';

$this->services['Sonata\\AdminBundle\\Command\\ListAdminCommand'] = $instance = new \Sonata\AdminBundle\Command\ListAdminCommand(($this->services['sonata.admin.pool'] ?? $this->getSonata_Admin_PoolService()));

$instance->setName('sonata:admin:list');

return $instance;
