<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\AdminBundle\Command\SetupAclCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Command/SetupAclCommand.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Util/AdminAclManipulatorInterface.php';
include_once $this->targetDirs[3].'/vendor/sonata-project/admin-bundle/src/Util/AdminAclManipulator.php';

$this->services['Sonata\\AdminBundle\\Command\\SetupAclCommand'] = $instance = new \Sonata\AdminBundle\Command\SetupAclCommand(($this->services['sonata.admin.pool'] ?? $this->getSonata_Admin_PoolService()), ($this->services['sonata.admin.manipulator.acl.admin'] ?? ($this->services['sonata.admin.manipulator.acl.admin'] = new \Sonata\AdminBundle\Util\AdminAclManipulator('Sonata\\AdminBundle\\Security\\Acl\\Permission\\MaskBuilder'))));

$instance->setName('sonata:admin:setup-acl');

return $instance;
