<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XxBBP_c' shared service.

return $this->privates['.service_locator.XxBBP_c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'author' => ['privates', '.errored..service_locator.XxBBP_c.App\\Entity\\Author', NULL, 'Cannot autowire service ".service_locator.XxBBP_c": it references class "App\\Entity\\Author" but no such service exists.'],
], [
    'author' => 'App\\Entity\\Author',
]);
