<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVDc2llr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVDc2llr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVDc2llr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVDc2llr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVDc2llr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VDc2llr',
    'container.build_id' => 'a5632377',
    'container.build_time' => 1574633346,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVDc2llr');
